export { crearDeck } from '../components/create-deck'
export { pedirCarta } from '../components/pedir-carta'
export { valorCarta } from '../components/valor-carta'
export { turnoComputadora } from '../components/turno-computadora'
export { crearCarta } from '../components/creat-carta'